version: '3.3'
services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      # - POSTGRES_DB=geodb
    ports:
      - 5438:5432
    volumes:
      - ./postgis:/docker-entrypoint-initdb.d

  nodejs:
    image: node:latest
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgis
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - 3500:3500
    command: sh -c "npm i && npm i -g nodemon && nodemon"

  tomcat:
    image: tomcat:8-jre11
    container_name: rtk_tomcat
    depends_on:
      - postgis
    volumes:
      - ./tomcat/:/usr/local/tomcat/webapps/
      # - ./tomcat/fonts/truetype/:/usr/share/fonts/truetype/
    ports:
      - 8080:8080
